# Generated by Django 5.1.6 on 2025-06-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
