# Generated by Django 5.1.6 on 2025-06-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_order_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='telegram_id',
        ),
    ]
