# Generated by Django 5.1.6 on 2025-06-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_order_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='telegram_id',
        ),
    ]
