# Generated by Django 5.1.6 on 2025-05-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='Не указан', max_length=50, verbose_name='Цвет'),
        ),
    ]
