# Generated by Django 5.1.6 on 2025-06-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='temp/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
