# Generated by Django 5.1.6 on 2025-06-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
