# Generated by Django 5.1.6 on 2025-06-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telegram ID'),
        ),
    ]
