# Generated by Django 5.1.6 on 2025-06-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tg_chat_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
